name: food_delivery_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  foldable_sidebar: ^1.0.0
  font_awesome_flutter:
  google_maps_flutter: ^2.0.1
  location: ^4.1.1
  geolocator: ^7.0.1
  geocoder: ^0.2.1
  provider: ^5.0.0
  permission_handler: ^6.1.1
  carousel_pro: ^1.0.0
  flutter_polyline_points: ^0.2.6
  slimy_card: ^1.0.4
  dropdown_formfield: ^0.1.3
  google_fonts: ^2.0.0
  cloud_firestore: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_core : ^1.0.2
  firebase_database: ^6.1.2
  flutter_colored_progress_indicators: ^1.2.0
  flappy_search_bar: ^1.7.2
  dio: ^4.0.0
  badges: ^2.0.1
  fluttertoast: ^8.0.6
  double_back_to_close_app: ^2.0.1
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.PNG
    - assets/images/panner_tikka.JPG
    - assets/images/dosa.jpg
    - assets/images/north_indian.JPG
    - assets/images/start_page.jpeg
    - assets/images/empty_shopping_cart.png
    - assets/images/search_not_found.PNG
    - assets/images/not_f.png
    - assets/images/drawer_header_background.png
    - assets/images/dp.png

    - assets/images/topmenu/north_indian.jpg
    - assets/images/topmenu/west_indian.png
    - assets/images/topmenu/maharashtrian.jpg
    - assets/images/topmenu/south_indian.jpeg
    - assets/images/topmenu/north_east_indian.jpg
    - assets/images/topmenu/bengali.jpg
    - assets/images/topmenu/all.jpg
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto-Bold.ttf
      - asset: assets/fonts/Roboto-Light.ttf

  - family: BerkshireSwash
    fonts:
      - asset: assets/fonts/BerkshireSwash-Regular.ttf

